---
title: "I really hope this gives P values"
author: "Braeden Grenier"
date: "2023-04-02"
output: html_document
---

So I think I have to remove all the P values from the ??? dataset, along with their gene ID, and then perform a bonferroni correction on all of them, then use the significance data from that and use it to plot the 

```{r}
okwhat = read.csv("FinalData.csv")
okwhat
#opens the final data set into this script
```

```{r}
hmm = data.frame(Gene = okwhat$Gene, 
                 PC3 = okwhat$P_C3_UT, 
                 PC8 = okwhat$P_C8_UT,
                 CS23 = okwhat$P_CS23_UT,
                 HS42 = okwhat$P_HS42_UT,
                 NC = okwhat$P_NC_UT)
hmm
#pulls out all the relevant P Values from the dataframe and creates a new dataframe, with their respective gene IDs
```

# Run Bonferonni, yeeaAAH!
```{r}
PC3Adj <- p.adjust(hmm$PC3, method = 'bonferroni')
PC8Adj = p.adjust(hmm$PC8, method = "bonferroni")
PCS23 = p.adjust(hmm$CS23, method = "bonferroni")
HS42Adj = p.adjust(hmm$HS42, method = "bonferroni")
PCAdj = p.adjust(hmm$NC, method = "bonferroni")
#This code takes the P values, and applies a bonferroni correction to each of them, and returns them as a string object
```

# Dataframe of P values
```{r}
Emperorsnewpvalues = data.frame(Gene = okwhat$Gene, 
                 PC3 = PC3Adj, 
                 PC8 = PC8Adj,
                 CS23 = PCS23,
                 HS42 = HS42Adj,
                 NC = PCAdj)
Emperorsnewpvalues
#this takes the adjusted bonferroni P values and puts them back into a new dataframe to make them easier to work with!
```

# Subset dataframe to only include significant p-values
```{r}
Emperorsnewpvalues %>% 
  mutate(p_adjusted=pAdj) %>%
  filter(p_adjusted <= 0.05)
#this filters the p values through a cutoff of a significance value of 0.05
```
